In [2]:
import torch
import denseconv

## padding的顺序
[←, →, ↑, ↓]

In [2]:
temp = torch.tensor([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
torch.nn.ZeroPad2d((1,2,3,4))(temp)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5,  0,  0],
        [ 0,  6,  7,  8,  9, 10,  0,  0],
        [ 0, 11, 12, 13, 14, 15,  0,  0],
        [ 0, 16, 17, 18, 19, 20,  0,  0],
        [ 0, 21, 22, 23, 24, 25,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [3]:
response = torch.tensor([[
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ], [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]
    ]
]], dtype=torch.float32)
print(response.shape)
impulse = torch.zeros(1, 3, 6, 6, dtype=torch.float32)
impulse[0, :, 0, 0] = 1
impulse[0, :, 4, 4] = 1
impulse[0, 1, 0, 0] = 0
impulse[0, 1, 1, 1] = 1
print(impulse)

torch.Size([1, 3, 3, 3])
tensor([[[[1., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0.]]]])


In [4]:
out = denseconv.sparseConv2d(response, impulse)
out

tensor([[[[ 1.,  2.,  3.,  0.,  0.,  0.],
          [ 4.,  5.,  6.,  0.,  0.,  0.],
          [ 7.,  8.,  9.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1.,  2.],
          [ 0.,  0.,  0.,  0.,  4.,  5.]],

         [[ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0., 10., 11., 12.,  0.,  0.],
          [ 0., 13., 14., 15.,  0.,  0.],
          [ 0., 16., 17., 18.,  0.,  0.],
          [ 0.,  0.,  0.,  0., 10., 11.],
          [ 0.,  0.,  0.,  0., 13., 14.]],

         [[19., 20., 21.,  0.,  0.,  0.],
          [22., 23., 24.,  0.,  0.,  0.],
          [25., 26., 27.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., 19., 20.],
          [ 0.,  0.,  0.,  0., 22., 23.]]]])

In [5]:
corr = denseconv.sparseCorr2d(response, out)
corr

tensor([[[[ 285.,  186.,   90.,    0.,    0.,    0.],
          [ 154.,   94.,   42.,    0.,    0.,    0.],
          [  50.,   26.,   18.,   26.,   41.,   48.],
          [   0.,    0.,   42.,   94.,  139.,  150.],
          [   0.,    0.,   63.,  135.,  195.,  207.],
          [   0.,    0.,   72.,  150.,  213.,  225.]],

         [[ 778., 1180.,  790.,  396.,    0.,    0.],
          [1212., 1824., 1212.,  603.,    0.,    0.],
          [ 790., 1180.,  958.,  752.,  545.,  561.],
          [ 380.,  563.,  752.,  958., 1147., 1176.],
          [   0.,    0.,  549., 1107., 1626., 1665.],
          [   0.,    0.,  585., 1176., 1725., 1764.]],

         [[4821., 3210., 1602.,    0.,    0.,    0.],
          [3178., 2110., 1050.,    0.,    0.,    0.],
          [1562., 1034., 1026., 1034., 1535., 1560.],
          [   0.,    0., 1050., 2110., 3127., 3174.],
          [   0.,    0., 1521., 3051., 4515., 4581.],
          [   0.,    0., 1584., 3174., 4695., 4761.]]]])

In [6]:
sum = 0
for i in range(1,9):
    sum += i * i
print(sum)

204


In [8]:
import time

## 卷积与反卷积
反卷积其实是信号中的卷积，padding视为做完卷积后边缘裁掉多少

In [28]:
aa = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
]], dtype=torch.float32).view(1,1,5,3)
bb = torch.tensor([[
    [1, 0, 1, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
]], dtype=torch.float32).view(1,1,6,4)

start_time = time.time()
conv_result = torch.nn.functional.conv2d(torch.nn.ZeroPad2d((2,0,4,0))(bb), torch.flip(aa, [-1,-2]))
end_time = time.time()
print(end_time - start_time)
print(conv_result)

start_time = time.time()
deconv_result = torch.nn.functional.conv_transpose2d(torch.nn.ZeroPad2d((2,0,4,0))(bb), aa, padding=(4,2))
end_time = time.time()
print(end_time - start_time)
print(deconv_result)

0.001018524169921875
tensor([[[[ 1.,  2.,  4.,  2.],
          [ 4.,  5., 10.,  5.],
          [ 7.,  8., 16.,  8.],
          [10., 11., 22., 11.],
          [13., 14., 28., 14.],
          [ 0.,  0.,  0.,  0.]]]])
0.0005118846893310547
tensor([[[[ 1.,  2.,  4.,  2.],
          [ 4.,  5., 10.,  5.],
          [ 7.,  8., 16.,  8.],
          [10., 11., 22., 11.],
          [13., 14., 28., 14.],
          [ 0.,  0.,  0.,  0.]]]])


In [29]:
temp = torch.nn.functional.conv_transpose2d(
    bb, aa,
    padding=(1,0)
)
print(temp.shape)
print(temp)

torch.Size([1, 1, 8, 6])
tensor([[[[ 4.,  5., 10.,  5.,  6.,  0.],
          [ 7.,  8., 16.,  8.,  9.,  0.],
          [10., 11., 22., 11., 12.,  0.],
          [13., 14., 28., 14., 15.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.]]]])


In [33]:
t = temp[:, :, 0:6, 0:4].view(1, 2, 3, 4)
t

tensor([[[[ 4.,  5., 10.,  5.],
          [ 7.,  8., 16.,  8.],
          [10., 11., 22., 11.]],

         [[13., 14., 28., 14.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]]]])

In [26]:
t[0,0,0,0] = 3

In [27]:
temp

tensor([[[[ 3.,  2.,  3.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  4.,  5.,  6.],
          [ 7.,  8.,  9.,  7.,  8.,  9.],
          [10., 11., 12., 10., 11., 12.],
          [13., 14., 15., 13., 14., 15.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.]]]])